GET http://localhost:3003/users
###

GET http://localhost:3003/products
###

GET http://localhost:3003/products/search?q=Produto2
###

POST http://localhost:3003/users
Content-Type: application/json

{
  "id": "u009",
  "name": "JoaolLucaslimaDev",
  "email": "joaolLucaslimadev@email.com",
  "password": "joaoL8lucasdev00"
}

###

POST http://localhost:3003/products
Content-Type: application/json

{
    "id": "p7",
    "name": "Teclado gamer",
    "price": 200,
    "description": "Teclado mecânico com numpad",
    "imageUrl": "https://teste/teste/Tecladogamer/teste"
}
###

### Deletar Usuário por ID

DELETE http://localhost:3003/users/004
Content-Type: application/json

###


### Deletar Produto por ID

DELETE http://localhost:3003/products/p5
Content-Type: application/json



### Editar produto por ID

# Edição do Produto p1
PUT http://localhost:3003/products/p3
Content-Type: application/json

{
    "name": "Mesa Gamer10",
    "price": 499.99,
    "description": "Mesa gamer top10",
    "image_url": "https://teste2103/teste23/mesagamer3/teste"
}
###


GET  http://localhost:3003/purchases
###


POST http://localhost:3003/purchases
Content-Type: application/json

  {
    "id": "p021",  
    "buyer_id": "003", 
    "id_product": "p3", 
    "quantity": 3 
  }
###
vv

DELETE http://localhost:3003/purchases/p021
Content-Type: application/json
###


# GET /purchases/:id
GET http://localhost:3003/purchases/p012
Content-Type: application/json
###

